name: stixproj
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - expat=2.7.3=h885b0b7_4
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libmpdec=4.0.0=h827c3e9_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - mkl=2025.3.0=hac47afa_455
  - numpy=2.4.1=py313hce7ae62_0
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyhc872135_0
  - python=3.13.10=h260b955_100_cp313
  - python_abi=3.13=3_cp313
  - setuptools=80.9.0=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - blis==1.3.3
    - catalogue==2.0.10
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpathlib==0.23.0
    - colorama==0.4.6
    - colour==0.1.5
    - confection==0.1.5
    - cymem==2.0.13
    - deepdiff==8.6.1
    - drawsvg==2.4.1
    - en-core-web-sm==3.8.0
    - et-xmlfile==2.0.0
    - greenlet==3.3.0
    - idna==3.11
    - jinja2==3.1.6
    - loguru==0.7.3
    - markdown==3.10
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - mdurl==0.1.2
    - mitreattack-python==5.3.0
    - murmurhash==1.0.15
    - mysql-connector-python==9.5.0
    - openpyxl==3.1.5
    - orderly-set==5.5.0
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.1.0
    - platformdirs==4.5.1
    - pooch==1.8.2
    - preshed==3.0.12
    - psycopg2==2.9.11
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pygments==2.19.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - requests==2.32.5
    - rich==14.2.0
    - shellingham==1.5.4
    - simplejson==3.20.2
    - six==1.17.0
    - smart-open==7.5.0
    - spacy==3.8.11
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sqlalchemy==2.0.45
    - srsly==2.5.2
    - stix2==3.0.1
    - stix2-patterns==2.0.0
    - tabulate==0.9.0
    - thinc==8.3.10
    - tqdm==4.67.1
    - typer==0.21.1
    - typer-slim==0.21.1
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.3
    - urllib3==2.6.3
    - wasabi==1.1.3
    - weasel==0.4.3
    - win32-setctime==1.2.0
    - wrapt==2.0.1
    - xlsxwriter==3.2.9
prefix: C:\Users\derek\anaconda3\envs\stixproj
